#更新fork
name: update fork

on: 
   workflow_dispatch:
   schedule:
     - cron: '50 7 * * *' #设置定时任务
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.owner.id == github.event.sender.id && github.actor != 'jerryc127' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.WORKFLOW_TOKEN }}
    - name: Install git
      run: |
        sudo apt-get update
        sudo apt-get -y install git
    - name: Set env
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Update fork
      run: |
        git remote add upstream https://github.com/jerryc127/hexo-theme-butterfly.git
        git remote -v
        git fetch upstream
        git checkout dev
        git merge --strategy-option=ours upstream/dev
        git push -f origin dev
